<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="UserApp.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    test
    <div class="jumbotron">
        <h1>User</h1>
        <p class="lead">EMPLOYEE TABLE</p>
         <table>
            <tr>
                <td>
                    <fieldset>
                        <asp:Label ID="lblMessage" runat="server"></asp:Label>
                    </fieldset>
                </td>
            </tr>
              <tr>
                <td>
                    <asp:Label ID="lblempname" runat="server" Text="empname"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtempname" runat="server" CausesValidation="True" ></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtempname" ErrorMessage="RequiredFieldValidator" ForeColor="#CC3300">Enter Employee Name</asp:RequiredFieldValidator>
                </td>
            </tr>
             <tr>
             <td>
                    <asp:Label ID="lblempsex" runat="server" Text="empsex"></asp:Label>
                </td>
                <td>
                    <asp:DropDownList ID="DropDownSex" runat="server">
                        <asp:ListItem>Male</asp:ListItem>
                        <asp:ListItem>FeMale</asp:ListItem>
                    </asp:DropDownList>
                </td>
            </tr>
             <tr>
                <td>
                    <asp:Label ID="lblempage" runat="server" Text="Emp Age"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtAge" runat="server"></asp:TextBox>
                </td>
            </tr>
             <tr>
                <td>
                    <asp:Button ID="btnSubmit" runat="server" Text="Submit" OnClick="btnSubmit_Click" />
                </td>
                <td>
                    <asp:Button ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click" />
                </td>
            </tr>

            <tr>
                <td>&nbsp;</td>
                <td>
                    <asp:HiddenField ID="empid" runat="server" />
                </td>
            </tr>
             
        </table>

    </div>
    <div>
        <table>
            <tr>
                <td colspan="2">
                    <asp:GridView ID="GridView1" runat="server"
                        AutoGenerateColumns="false" AllowPaging="true" AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AllowCustomPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" DataKeyNames="empid" OnRowDeleting="GridView1_RowDeleting">
                        <AlternatingRowStyle BackColor="#99CCFF" BorderColor="#99CCFF" />
                        <Columns>
                            <asp:BoundField ItemStyle-Width="150px" DataField="empid" HeaderText="Emp Id">
                                <ItemStyle Width="150px"></ItemStyle>
                            </asp:BoundField>
                            <asp:BoundField ItemStyle-Width="150px" DataField="empname" HeaderText="Emp Name">
                                <ItemStyle Width="150px"></ItemStyle>
                            </asp:BoundField>
               
                            <asp:BoundField ItemStyle-Width="150px" DataField="empage" HeaderText="Emp Age">
                                <ItemStyle Width="150px"></ItemStyle>
                            </asp:BoundField>
                            <asp:BoundField ItemStyle-Width="150px" DataField="empsex" HeaderText="Emp Sex">

                                <ItemStyle Width="150px"></ItemStyle>
                            </asp:BoundField>

                        </Columns>
                        <HeaderStyle BackColor="#FF3399" BorderColor="#FF33CC" />
                    </asp:GridView>
                </td>

            </tr>

        </table>
    </div>
</asp:Content>

