<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="UserApp._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="jumbotron">
        <h1>User</h1>
        <p class="lead">User Web applications using ASP.NET, HTML, CSS, JavaScript, SQL Server with stored procedure.</p>


        <table>
            <tr>
                <td>
                    <fieldset>
                        <asp:Label ID="lblMessage" runat="server"></asp:Label>
                    </fieldset>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="lblFirstName" runat="server" Text="FirstName"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtFirstName" runat="server" CausesValidation="True" OnTextChanged="txtFirstName_TextChanged"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtFirstName" ErrorMessage="RequiredFieldValidator" ForeColor="#CC3300">Enter First Name</asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="lblLastName" runat="server" Text="LastName"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtLastName" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="lblSex" runat="server" Text="Sex"></asp:Label>
                </td>
                <td>
                    <asp:DropDownList ID="DropDownSex" runat="server">
                        <asp:ListItem>Male</asp:ListItem>
                        <asp:ListItem>FeMale</asp:ListItem>
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="lblAge" runat="server" Text="Age"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtAge" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Button ID="btnSubmit" runat="server" Text="Submit" OnClick="btnSubmit_Click" />
                </td>
                <td>
                    <asp:Button ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click" />
                </td>
            </tr>

            <tr>
                <td>&nbsp;</td>
                <td>
                    <asp:HiddenField ID="hUserid" runat="server" />
                </td>
            </tr>



        </table>

    </div>
    <div>
        <table>
            <tr>
                <td colspan="2">
                    <asp:GridView ID="GridView1" runat="server"
                        AutoGenerateColumns="false" AllowPaging="true" AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AllowCustomPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" DataKeyNames="UserId" OnRowDeleting="GridView1_RowDeleting">
                        <AlternatingRowStyle BackColor="#99CCFF" BorderColor="#99CCFF" />
                        <Columns>
                            <asp:BoundField ItemStyle-Width="150px" DataField="UserID" HeaderText="User ID">
                                <ItemStyle Width="150px"></ItemStyle>
                            </asp:BoundField>
                            <asp:BoundField ItemStyle-Width="150px" DataField="FirstName" HeaderText="First Name">
                                <ItemStyle Width="150px"></ItemStyle>
                            </asp:BoundField>
                            <asp:BoundField ItemStyle-Width="150px" DataField="LastName" HeaderText="Last Name">
                                <ItemStyle Width="150px"></ItemStyle>
                            </asp:BoundField>
                            <asp:BoundField ItemStyle-Width="150px" DataField="Age" HeaderText="Age">
                                <ItemStyle Width="150px"></ItemStyle>
                            </asp:BoundField>
                            <asp:BoundField ItemStyle-Width="150px" DataField="Sex" HeaderText="Sex">

                                <ItemStyle Width="150px"></ItemStyle>
                            </asp:BoundField>

                        </Columns>
                        <HeaderStyle BackColor="#FF3399" BorderColor="#FF33CC" />
                    </asp:GridView>
                </td>

            </tr>

        </table>
    </div>
</asp:Content>
